pipeline { 
    agent any

    tools{
	maven 'maven 3.9.8'
    }

    stages{ 
        stage('build'){
when{ changeset "**/worker/**" } 
            steps{ 
                echo 'building worker app' 
                dir('worker'){ 
                  sh 'mvn compile' 
                } 
            } 
        } 
        stage('test'){ 
when{ changeset "**/worker/**" }
            steps{ 
                echo 'running unit tests on worker app' 
		dir('worker'){
			sh 'mvn compile'
		}
         
            } 
        } 
        stage('package'){ 
when{ changeset "**/worker/**" }
            steps{ 
                echo 'packaging worker app'
		dir('worker') {
			sh 'mvn package -DskipTests'
		} 
            } 
        } 
    }
    post{ 
        always{ 
            	archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
		echo 'Building multibranch pipeline for worker is completed.' 
	
    }
  }
}
